#ifndef _MW_AHRS_DEFINE_H
#define _MW_AHRS_DEFINE_H

enum AccessCode
{
  AC_OBJECT_WRITE_REQ = 0x10,
  AC_OBJECT_WRITE_RES = 0x20,
  AC_OBJECT_READ_REQ  = 0x30,
  AC_OBJECT_READ_RES  = 0x40,
  AC_OBJECT_ERROR_RES = 0x80
};

enum ObjectType
{
  OT_INT8  = 0x00,
  OT_INT16 = 0x04,
  OT_INT32 = 0x08,
  OT_FLOAT = 0x0C
};

enum ErrorCode
{
  UNDEFINED_NAME         = 1,
  PACKET_FORMAT_ERROR    = 2,
  OBJECT_ACCESS_ERROR    = 3,
  WRONG_VALUE_ASSIGNMENT = 4
};

enum MW_AHRS_INDEX
{
  PROVIDER_ID = 1,
  PRODUCT_ID,
  SOFTWARE_VERSION,
  HARDWARE_VERSION,  // RO
  COMMAND   = 7,     // WO
  DEVICE_ID = 11,
  CAN_BUS_SPEED,
  SERIAL_BUS_SPEED,  // RW
  MAGNETIC_VARIANCE = 19,
  ACCELEROMETER_VARIANCE,  // RW
  SET_SERIAL_DATA = 21,
  SET_CAN_DATA,     // RW
  SET_PERIOD = 24,  // RW

  // FLOAT
  ACCELERATION = 51,
  GYROSCOPE,
  ANGLE,
  MAGNETIC,         // RO
  TEMPERATURE = 57  // RO
};

enum MW_AHRS_DATA_TYPE_LIST
{
  DT_NONE =0,
  DT_ACC,
  DT_GYRO,
  DT_ANGLE,
  DT_MAGNETIC
};

#endif