config_name: DOOR_CONTROL_CONFIG
can:
  send_id: 320 # 0x140
  reply_id: 576 # 0x240
  channel: 0
  bitrate: -1
  retry_turm: 2
  retry_count: 3
thread:
  hz: 100
rmd_comm:
  gear_ratio: 36
  step_per_rev: 16384
  rpm: 15
