// Generated by gencpp from file smart_cargo_package/action_complete_msgs.msg
// DO NOT EDIT!


#ifndef SMART_CARGO_PACKAGE_MESSAGE_ACTION_COMPLETE_MSGS_H
#define SMART_CARGO_PACKAGE_MESSAGE_ACTION_COMPLETE_MSGS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace smart_cargo_package
{
template <class ContainerAllocator>
struct action_complete_msgs_
{
  typedef action_complete_msgs_<ContainerAllocator> Type;

  action_complete_msgs_()
    : time_stamp()
    , receive_object(0)
    , action_object(0)
    , complete_action(0)
    , error_code(0)  {
    }
  action_complete_msgs_(const ContainerAllocator& _alloc)
    : time_stamp()
    , receive_object(0)
    , action_object(0)
    , complete_action(0)
    , error_code(0)  {
  (void)_alloc;
    }



   typedef ros::Time _time_stamp_type;
  _time_stamp_type time_stamp;

   typedef int32_t _receive_object_type;
  _receive_object_type receive_object;

   typedef int32_t _action_object_type;
  _action_object_type action_object;

   typedef int32_t _complete_action_type;
  _complete_action_type complete_action;

   typedef int32_t _error_code_type;
  _error_code_type error_code;





  typedef boost::shared_ptr< ::smart_cargo_package::action_complete_msgs_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::smart_cargo_package::action_complete_msgs_<ContainerAllocator> const> ConstPtr;

}; // struct action_complete_msgs_

typedef ::smart_cargo_package::action_complete_msgs_<std::allocator<void> > action_complete_msgs;

typedef boost::shared_ptr< ::smart_cargo_package::action_complete_msgs > action_complete_msgsPtr;
typedef boost::shared_ptr< ::smart_cargo_package::action_complete_msgs const> action_complete_msgsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::smart_cargo_package::action_complete_msgs_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::smart_cargo_package::action_complete_msgs_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::smart_cargo_package::action_complete_msgs_<ContainerAllocator1> & lhs, const ::smart_cargo_package::action_complete_msgs_<ContainerAllocator2> & rhs)
{
  return lhs.time_stamp == rhs.time_stamp &&
    lhs.receive_object == rhs.receive_object &&
    lhs.action_object == rhs.action_object &&
    lhs.complete_action == rhs.complete_action &&
    lhs.error_code == rhs.error_code;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::smart_cargo_package::action_complete_msgs_<ContainerAllocator1> & lhs, const ::smart_cargo_package::action_complete_msgs_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace smart_cargo_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::smart_cargo_package::action_complete_msgs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smart_cargo_package::action_complete_msgs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::smart_cargo_package::action_complete_msgs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::smart_cargo_package::action_complete_msgs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smart_cargo_package::action_complete_msgs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smart_cargo_package::action_complete_msgs_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::smart_cargo_package::action_complete_msgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8cfdf36b4b872dd50c9838483632d5fd";
  }

  static const char* value(const ::smart_cargo_package::action_complete_msgs_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8cfdf36b4b872dd5ULL;
  static const uint64_t static_value2 = 0x0c9838483632d5fdULL;
};

template<class ContainerAllocator>
struct DataType< ::smart_cargo_package::action_complete_msgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "smart_cargo_package/action_complete_msgs";
  }

  static const char* value(const ::smart_cargo_package::action_complete_msgs_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::smart_cargo_package::action_complete_msgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time time_stamp       # Message 발행 시간 (ros::Time)\n"
"int32 receive_object    # 수신 객체 H/W Index Enum   <----- 꼭 필요한지 생각해보자 \n"
"int32 action_object    # 동작 객체 H/W Index Enum\n"
"int32 complete_action  # 완료 동작 Action Index Enum (짝수만 와야 한다)\n"
"int32 error_code       # Error-Code\n"
;
  }

  static const char* value(const ::smart_cargo_package::action_complete_msgs_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::smart_cargo_package::action_complete_msgs_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.time_stamp);
      stream.next(m.receive_object);
      stream.next(m.action_object);
      stream.next(m.complete_action);
      stream.next(m.error_code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct action_complete_msgs_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::smart_cargo_package::action_complete_msgs_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::smart_cargo_package::action_complete_msgs_<ContainerAllocator>& v)
  {
    s << indent << "time_stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.time_stamp);
    s << indent << "receive_object: ";
    Printer<int32_t>::stream(s, indent + "  ", v.receive_object);
    s << indent << "action_object: ";
    Printer<int32_t>::stream(s, indent + "  ", v.action_object);
    s << indent << "complete_action: ";
    Printer<int32_t>::stream(s, indent + "  ", v.complete_action);
    s << indent << "error_code: ";
    Printer<int32_t>::stream(s, indent + "  ", v.error_code);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SMART_CARGO_PACKAGE_MESSAGE_ACTION_COMPLETE_MSGS_H
